[package]
name = "bevy_bracket_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.6.0"
bracket-lib = { version = "0.8.1", default-features = false }
